webapp/blueprints/answers.py
import flask
import flask_login
from flask.blueprints import Blueprint
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm.exc import NoResultFound
from datetime import datetime
from collections import defaultdict
import json

import colorsys
import blueprints.lessons as lessons
import blueprints.users as users
from blueprints.lessons import Chapter, QuestionsList
from database import db



answers = Blueprint(
    'answers',
    __name__,
    template_folder='templates',
    static_folder='static',
)

class Answers(db.Model):
    chapter_id =db.Column(db.Text, db.ForeignKey('chapter.id', ondelete="CASCADE"), primary_key=True)
    user_id = db.Column(db.Text, db.ForeignKey('users.email', ondelete="CASCADE"), primary_key=True)
    answers_str = db.Column(JSON)

    def nb_answered(self):
        return len([
            a for a in self.answers['questions']
            if a['answer']
        ])

    @property
    def answers(self):
        try:
            return self._answers
        except AttributeError:
            self._answers = json.loads(self.answers_str)
            return self._answers

    @answers.setter
    def answers(self, answers):
        self.answers_str = json.dumps(answers)
        self._answers = answers


def build_answers(chapter):
    return {
        'questions': [
            { 'title': q.title,
              'answer': None,
            }
            for q in chapter.questions_list
        ],
        'current_question': 0,
    }

def quizz_status(chapter, user):
    answer_object = Answers.query.get(
        (chapter.id, user.get_id())
    )

    if answer_object is None:
        res = "Not started"
    else:
        res = "Answered %d/%d" % (
          answer_object.nb_answered(),
          len(chapter.questions_list),
        )

    if chapter.state == lessons.QuestionState.CORRECTED:
        res = "Score: %.1f/%.1f" % compute_score(chapter, user)

    return res

def compute_score(chapter, user):
    answer_object = Answers.query.get((chapter.id, user.get_id()))
    questions = chapter.questions_list

    if answer_object is None:
        return 0., chapter.max_score()

    score = 0
    for question, answer in zip(questions, answer_object.answers['questions']):
        answer_text = answer['answer']
        grade = question.grade_by_answer.get(answer_text, 0)

        score += question.coefficient * grade / 4
    return score, chapter.max_score()



@answers.route('/quizz/<chapter_id>', methods=['GET'])
@flask_login.login_required
def answers_get(chapter_id):
    chapter = Chapter.query.get(chapter_id)
    if chapter is None:
        return flask.render_template(
            "error.html",
            message="The route %s does not exist!"%flask.request.path,
        )

    if chapter.state != lessons.QuestionState.PUBLISHED:
        return flask.render_template(
            "error.html",
            message="You can not answer this quizz!"
        )

    if flask.request.content_type != 'application/json':
        return flask.render_template('quizz.html', chapter_id=chapter_id)

    answers_object = Answers.query.get(
        (chapter_id,flask_login.current_user.get_id())
    )
    if answers_object is None:
        answers = build_answers(chapter)
    else:
        answers = answers_object.answers

    chapter_questions = [q.title for q in chapter.questions_list]
    answers_questions = [q['title'] for q in  answers['questions']]
    if  chapter_questions != answers_questions:
        answers = build_answers(chapter)

    return flask.jsonify(answers)

@answers.route('/quizz/<chapter_id>', methods=['POST'])
@flask_login.login_required
def answers_post(chapter_id):
    chapter = Chapter.query.get(chapter_id)
    if chapter is None:
        return flask.jsonify({"error": "chapter does not exist"}), 404

    if chapter.state != lessons.QuestionState.PUBLISHED:
        return flask.jsonify({"error": "deadline exceeded"}), 400

    chapter_questions = [q.title for q in chapter.questions_list]
    answers_questions = [q['title'] for q in  flask.request.json['questions']]
    if chapter_questions != answers_questions:
        return flask.jsonify({"error": "bad questions list"}), 400

    answers_object = Answers.query.get(
        (chapter_id,flask_login.current_user.get_id())
    )

    if answers_object is None:
        db.session.add(Answers(
            chapter_id=chapter_id,
            user_id=flask_login.current_user.get_id(),
            answers=flask.request.json,
        ))
    else:
        answers_object.answers = flask.request.json
    db.session.commit()
    return flask.jsonify({"status": "ok"})

@answers.route('/correct-quizz/<chapter_id>/', methods=['GET'])
@flask_login.login_required
def correct_quizz(chapter_id):
    if not flask_login.current_user.is_teacher:
        return flask.render_template('error.html', message="Not authorized"), 403

    chapter = Chapter.query.get(chapter_id)
    if chapter is None:
        return flask.render_template('error.html', message= "chapter does not exist"), 404

    return flask.render_template('correct-quizz.html', chapter_id=chapter.id)

@answers.route('/correct-quizz/<chapter_id>/questions/', methods=['GET'])
@flask_login.login_required
def get_questions(chapter_id):
    if not flask_login.current_user.is_teacher:
        return flask.jsonify({"error": "not authorized"}), 403

    chapter = Chapter.query.get(chapter_id)
    if chapter is None:
        return flask.jsonify({"error": "chapter does not exist"}), 404

    return questions_json(chapter)


@answers.route('/correct-quizz/<chapter_id>/mark-answer/', methods=['POST'])
@flask_login.login_required
def mark_answer(chapter_id):
    if not flask_login.current_user.is_teacher:
        return flask.jsonify({"error": "not authorized"}), 403

    chapter = Chapter.query.get(chapter_id)
    if chapter is None:
        return flask.jsonify({"error": "chapter does not exist"}), 404

    questions = chapter.questions_list
    questionNumber = flask.request.json['questionNumber']
    answer = flask.request.json['answer']
    mark = flask.request.json['mark']

    questions.questions[questionNumber].grade_by_answer[answer] = mark

    chapter.questions_list = questions
    db.session.commit()

    return questions_json(chapter)

def compute_color(score, max_score):
    if max_score == 0:
        return "rgb(255, 0, 0)"

    ratio = score/max_score

    hue = 120 *  ratio / 360
    sat = 0.5 + abs(ratio - 0.5)
    val = 1

    (red, green, blue) = colorsys.hsv_to_rgb(hue, sat, val)
    return "rgb(%d, %d, %d)"%(red*255, green*255, blue*255)

@answers.route('/solutions/<chapter_id>/')
def see_solutions(chapter_id):
    chapter = Chapter.query.get(chapter_id)
    if chapter is None:
        return flask.render_template(
            "error.html",
            message="The route %s does not exist!"%flask.request.path,
        )

    if chapter.state != lessons.QuestionState.CORRECTED:
        return flask.render_template(
            "error.html",
            message="You can not see the solution yet!"
        )

    student_answers = Answers.query.filter_by(
            chapter_id=chapter_id,
            user_id=flask_login.current_user.get_id(),
    ).first()

    teachers_answers = Answers.query.filter_by(
                chapter_id=chapter_id
        ).join(
            users.User
        ).filter_by(
                is_teacher=True
        ).all()

    questions = [
        {
            'title': question.title,
            'coefficient': question.coefficient,
            'student_answer': student_answer['answer'],
            'teachers_answer': [a['answer'] for a in teacher_answers],
            'grade': question.grade_by_answer.get(student_answer['answer'], None)
        }
        for question, student_answer, teacher_answers in zip(
            chapter.questions_list,
            student_answers.answers['questions'],
            zip(*( a.answers['questions'] for a in teachers_answers))
        )
    ]

    return flask.render_template('see-solutions.html',
        questions=questions,
        chapter_id=chapter_id,
        score=compute_score(chapter, flask_login.current_user),
    )



@answers.route('/see-results/', methods=['GET'])
@flask_login.login_required
def see_results():
    if not flask_login.current_user.is_teacher:
        return flask.render_template("error.html", message= "not authorized"), 403

    userlist = users.User.query.order_by('email').all()
    chapters = Chapter.query.order_by('id').all()
    users_with_marks = []
    for u in userlist:
        marks = []
        for chapter in chapters:
            score, max_score = compute_score(chapter, u)
            color = compute_color(score, max_score)
            marks.append((score, max_score, color))

        users_with_marks.append({
            'email': u.email
            , 'name': u.name
            , 'marks': marks
            , 'total': sum(m[0] for m in marks)
            , 'total_max': sum(m[1] for m in marks)
        })

    return flask.render_template("results.html",
        users_with_marks=users_with_marks,
        chapters=chapters
    )


def questions_json(chapter):
    questions = chapter.questions_list
    answers_objects = Answers.query.filter_by(chapter_id=chapter.id).all()
    users_dict = { u.get_id(): u for u in users.User.query.all()}

    def get_answers_from_question(i):
        answers = [
            {
                'student': users_dict[answer_object.user_id],
                'answer':  answer_object.answers['questions'][i]['answer']
            }
            for answer_object in answers_objects
        ]

        res = defaultdict(list)
        for answer in answers:
            res[answer['answer']].append(answer['student'].name)

        try:
            res.pop(None)
        except KeyError:
            pass

        return [
            {'students': students, 'answer': answer}
            for answer, students in res.items()
        ]

webapp/blueprints/users.py
import os
import base64

import flask
import flask_login
from flask.blueprints import Blueprint
from werkzeug.security import generate_password_hash, check_password_hash

from database import db
import settings

users = Blueprint(
    'users',
    __name__,
    template_folder='templates',
    static_folder='static',
)

class User(flask_login.UserMixin, db.Model):
    __tablename__ = "users"
    email = db.Column(db.Text, primary_key=True)
    name = db.Column(db.Text)
    is_teacher = db.Column(db.Boolean, default=False)
    token_for_register=db.Column(db.Text)
    password_hash = db.Column(db.Text)

    def get_id(self):
        return self.email

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


def create_users(names_emails, mailer):
    for name, email in names_emails:
        token = base64.urlsafe_b64encode(os.urandom(51)).decode()
        user = User(
            name=name,
            email=email,
            token_for_register=token,
        )

        db.session.add(user)
        try:
            db.session.commit()
            mailer.send_message(
                subject='Your account on "The Learning Web Server"',
                body="""Hello %s,
    An account has been created for you on the website %s . Follow the
    previous link to define your password!
                """%(
                    name,
                    flask.url_for('users.redefine_password', email=email, token=token),
                ),
                sender=settings.MAIL_DEFAULT_SENDER,
                recipients=[email],
            )
        except IntegrityError:
            db.session.rollback()





@users.route('/redefine_password/<email>/<token>', methods=['GET', 'POST'])
def redefine_password(email, token):
    user = User.query.get(email)

    redir_home = flask.redirect(flask.url_for('home'))
    if user is None or user.token_for_register != token:
        flask.flash("Something went wrong...")
        return redir_home

    if flask.request.method == 'GET':
        return flask.render_template('redefine_password.html')

    # POST method assumed here:
    password1 = flask.request.form.get('password1')
    password2 = flask.request.form.get('password2')

    if password1 is None or password2 is None:
        flask.flash("Please fulfill the two password fields")
        return flask.render_template('redefine_password.html')

    if password1 != password2:
        flask.flash("The passwords did not match")
        return flask.render_template('redefine_password.html')

    user.set_password(password1)
    user.token_for_register = None
    db.session.commit()

    remember = flask.request.form.get('remember_me')
    flask_login.login_user(user, remember=remember)
    return redir_home


@users.route('/login', methods=['POST'])
def login_post():
    email = flask.request.form.get('email')
    password = flask.request.form.get('password')
    remember = flask.request.form.get('remember_me')
    if not email or not password:
        flask.flash("Please provide your email and your password.")
        return flask.redirect(flask.url_for('users.login_get'))


    user = User.query.get(email)
    if user is None or not user.check_password(password):
        flask.flash("Authentication failed")
        return flask.redirect(flask.url_for('users.login_get'))


    flask_login.login_user(user, remember=remember)
    flask.flash("Logged in as %s!" % email)
    return flask.redirect(flask.url_for('home'))

@users.route('/login', methods=['GET'])
def login_get():
    return flask.render_template('login.html')

@users.route('/logout')
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for('users.login_get'))

webapp/templates/chapter_form.html
{% extends "layout.html" %}

{% block title %}Chapter edition{% endblock %}

{% block head %}
<script type="text/javascript" src="/static/quizz_creator.js"></script>
{% endblock head %}


{% block content %}
<div id="creator-app" ></div>
<script type="text/javascript">
    var node = document.getElementById('creator-app');
    var app = Elm.QuizzCreator.init({
      node: node,
      flags :{
        creation : {% if creation %}true{% else %}false{% endif %}
      }
    });
</script>

{% endblock %}

webapp/templates/correct-quizz.html
{% extends "layout.html" %}

{% block title %}{{ chapter_name }} - quizz correction{% endblock %}

{% block head %}
<script type="text/javascript" src="/static/quizz_corrector.js"></script>
{% endblock head %}

{% block content %}
<div id="corrector-app" data-quizzname="{{ chapter_id }}"></div>
<script type="text/javascript">
    var node = document.getElementById('corrector-app');
    var app = Elm.QuizzCorrector.init({
      node: node,
      flags :{
        quizzName : node.dataset.quizzname
      }
    });
</script>
{% endblock %}

webapp/templates/error.html
{% extends "layout.html" %}

{% block content %}
    <p>{{ message }}</p>
    <a href="/">Back to home</a>
{% endblock %}

webapp/templates/home.html
{% extends "layout.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<p>Here are the quizzes:
</p>
{% if current_user.is_teacher %}
    <ul>
        <li><a href="{{ url_for('answers.see_results') }}">
            See the student's results
        </a></li>
        <li><a href="{{ url_for('lessons.new_chapter') }}">
            Create a chapter
            </a>
        </li>
        <li><a href="{{ url_for('lessons.export') }}">
            Export all the chapters
            </a>
        </li>
    </ul>
{% endif %}
<table>
    <thead>
        <th>Quizz</th>
        <th>Status</th>
        {% if current_user.is_teacher %}
        <th>Correction</th>
        {% endif %}
    </thead>
    <tbody>

        {% for chapter in chapters %}
        <tr>
            <td>
                {% if current_user.is_teacher %}
                    <a href="{{ url_for('lessons.edit_chapter', chapter_id=chapter.id)}}">
                        {{ chapter.id }}
                    </a>
                {% else %}
                    {{ chapter.id }}
                {% endif %}
            </td>
            <td>
                {% if chapter.state.value == "PUBLISHED" %}
                    <a href="{{ url_for('answers.answers_get', chapter_id=chapter.id) }}">
                        {{ chapter.quizz_status }}
                    </a>
                {% elif chapter.state.value == "WAITING_FOR_CORRECTION" %}
                    Correction in progress...
                {% elif chapter.state.value == "CORRECTED" %}
                    <a href="{{ url_for('answers.see_solutions', chapter_id=chapter.id) }}">
                        {{ chapter.quizz_status }}
                    </a>
                {% endif %}
                </a>
            </td>
            {% if current_user.is_teacher %}
            <td>
                <a href="{{ url_for('answers.correct_quizz', chapter_id=chapter.id) }}">
                    Go to correction
                </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

webapp/templates/layout.html
<!doctype html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <meta charset="utf-8">
    {% block head %}{% endblock %}
</head>
<body>
    <h1><a href="/">Quizz server</a></h1>
    <nav>
        {% if current_user.is_authenticated %}
          <div><span>{{ current_user.email }}</span>
          &ndash;<a href="{{ url_for('users.logout') }}">Log out</a>
        </div>
        {% endif %}
    </nav>
    <section class="content">
      <header>
        {% block header %}{% endblock %}
      </header>
      {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
      {% endfor %}
      {% block content %}{% endblock %}
    </section>
</body>
</html>

webapp/templates/login.html
{% extends "layout.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
<h2>Log in</h2>

<form method="POST" action="/login">
    <label>Email: <input type="email" name="email" /></label>
    <label>Password: <input type="password" name="password" /></label>
    <input type="submit" name="" value="Send" />
</form>
{% endblock %}

webapp/templates/quizz.html
{% extends "layout.html" %}

{% block title %}Exercises{% endblock %}

{% block content %}
<div id="quizz-app" data-chapter-id="{{ chapter_id }}">
</div>
<script type="text/javascript" src="/static/dom_builder.js"></script>
<script type="text/javascript" src="/static/quizz.js"></script>
{% endblock %}

webapp/templates/redefine_password.html
{% extends "layout.html" %}

{% block title %}Define a new password{% endblock %}

{% block content %}
<h2>Hello {{ name }}</h2>

<p>Enter here your new password</p>
<form method="POST">
    <label>Password: <input type="password" name="password1"/></label><br />
    <label>Password again: <input type="password" name="password2"/></label><br />
    <input type="submit" value="Envoyer !"/>
</form>
{% endblock %}

webapp/templates/results.html
{% extends "layout.html" %}

{% block title %}Quizz results{% endblock %}

{% block head %}
<script type="text/javascript" src="/static/quizz_corrector.js"></script>
{% endblock head %}

{% block content %}
<h1>Results</h1>


<table>
    <thead>
        <tr>
            <th>Name</th>
            {% for chapter in chapters %}
                <th>{{ chapter.id }}</th>
            {% endfor %}
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for u in users_with_marks %}
            <tr>
                <th>
                    {{ u.name }}
                </th>
                {% for score, max_score, color in u.marks %}
                    <td style="background-color: {{ color }}">
                        {{ score }} / {{ max_score }}
                    </td>
                {% endfor %}
                <td>{{ u.total }} / {{ u.total_max }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

webapp/templates/see-solutions.html
{% extends "layout.html" %}

{% block title %}Solutions of {{ chapter_id }}{% endblock %}

{% block content %}
<h2>Solutions of {{ chapter_id }}</h2>

<p>Total score: {{ score[0] }} / {{ score[1] }}</p>

{% for question in questions %}
    <hr />
    <p><em>({{ question.coefficient }} points)</em> {{ question.title | safe }}</p>

    <p><strong>Your answer:</strong>
        <pre><code class="block padding">{{ question.student_answer }}</code></pre>
        {% if question.grade is not none %}
            <em>{{ question.grade }} / 4</em>
        {% else %}
            <em>Non-graded answer. Contact your teacher to be corrected!</em>
        {% endif %}
    </p>

    <strong>The teacher(s) answered:</strong>
    <ul>
        {% for answer in question.teachers_answer %}
           <li><pre><code class="block padding">{{ answer }}</code></pre></li>
        {% endfor %}
    </ul>
{% endfor %}

{% endblock %}